# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.11

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "C:\Program Files\CMake\bin\cmake.exe"

# The command to remove a file.
RM = "C:\Program Files\CMake\bin\cmake.exe" -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "D:\College\3rdYear\2ndTerm\Compilers\Project\Lexical Analysis\java-compiler"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "D:\College\3rdYear\2ndTerm\Compilers\Project\Lexical Analysis\java-compiler"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	"C:\Program Files\CMake\bin\cmake-gui.exe" -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	"C:\Program Files\CMake\bin\cmake.exe" -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "D:\College\3rdYear\2ndTerm\Compilers\Project\Lexical Analysis\java-compiler\CMakeFiles" "D:\College\3rdYear\2ndTerm\Compilers\Project\Lexical Analysis\java-compiler\CMakeFiles\progress.marks"
	$(MAKE) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "D:\College\3rdYear\2ndTerm\Compilers\Project\Lexical Analysis\java-compiler\CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named java_compiler

# Build rule for target.
java_compiler: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 java_compiler
.PHONY : java_compiler

# fast build rule for target.
java_compiler/fast:
	$(MAKE) -f CMakeFiles\java_compiler.dir\build.make CMakeFiles/java_compiler.dir/build
.PHONY : java_compiler/fast

lexical_analyzer_generator/finite_automata/finite_automata.obj: lexical_analyzer_generator/finite_automata/finite_automata.cpp.obj

.PHONY : lexical_analyzer_generator/finite_automata/finite_automata.obj

# target to build an object file
lexical_analyzer_generator/finite_automata/finite_automata.cpp.obj:
	$(MAKE) -f CMakeFiles\java_compiler.dir\build.make CMakeFiles/java_compiler.dir/lexical_analyzer_generator/finite_automata/finite_automata.cpp.obj
.PHONY : lexical_analyzer_generator/finite_automata/finite_automata.cpp.obj

lexical_analyzer_generator/finite_automata/finite_automata.i: lexical_analyzer_generator/finite_automata/finite_automata.cpp.i

.PHONY : lexical_analyzer_generator/finite_automata/finite_automata.i

# target to preprocess a source file
lexical_analyzer_generator/finite_automata/finite_automata.cpp.i:
	$(MAKE) -f CMakeFiles\java_compiler.dir\build.make CMakeFiles/java_compiler.dir/lexical_analyzer_generator/finite_automata/finite_automata.cpp.i
.PHONY : lexical_analyzer_generator/finite_automata/finite_automata.cpp.i

lexical_analyzer_generator/finite_automata/finite_automata.s: lexical_analyzer_generator/finite_automata/finite_automata.cpp.s

.PHONY : lexical_analyzer_generator/finite_automata/finite_automata.s

# target to generate assembly for a file
lexical_analyzer_generator/finite_automata/finite_automata.cpp.s:
	$(MAKE) -f CMakeFiles\java_compiler.dir\build.make CMakeFiles/java_compiler.dir/lexical_analyzer_generator/finite_automata/finite_automata.cpp.s
.PHONY : lexical_analyzer_generator/finite_automata/finite_automata.cpp.s

lexical_analyzer_generator/finite_automata/state.obj: lexical_analyzer_generator/finite_automata/state.cpp.obj

.PHONY : lexical_analyzer_generator/finite_automata/state.obj

# target to build an object file
lexical_analyzer_generator/finite_automata/state.cpp.obj:
	$(MAKE) -f CMakeFiles\java_compiler.dir\build.make CMakeFiles/java_compiler.dir/lexical_analyzer_generator/finite_automata/state.cpp.obj
.PHONY : lexical_analyzer_generator/finite_automata/state.cpp.obj

lexical_analyzer_generator/finite_automata/state.i: lexical_analyzer_generator/finite_automata/state.cpp.i

.PHONY : lexical_analyzer_generator/finite_automata/state.i

# target to preprocess a source file
lexical_analyzer_generator/finite_automata/state.cpp.i:
	$(MAKE) -f CMakeFiles\java_compiler.dir\build.make CMakeFiles/java_compiler.dir/lexical_analyzer_generator/finite_automata/state.cpp.i
.PHONY : lexical_analyzer_generator/finite_automata/state.cpp.i

lexical_analyzer_generator/finite_automata/state.s: lexical_analyzer_generator/finite_automata/state.cpp.s

.PHONY : lexical_analyzer_generator/finite_automata/state.s

# target to generate assembly for a file
lexical_analyzer_generator/finite_automata/state.cpp.s:
	$(MAKE) -f CMakeFiles\java_compiler.dir\build.make CMakeFiles/java_compiler.dir/lexical_analyzer_generator/finite_automata/state.cpp.s
.PHONY : lexical_analyzer_generator/finite_automata/state.cpp.s

lexical_analyzer_generator/lexical_analyzer_generator.obj: lexical_analyzer_generator/lexical_analyzer_generator.cpp.obj

.PHONY : lexical_analyzer_generator/lexical_analyzer_generator.obj

# target to build an object file
lexical_analyzer_generator/lexical_analyzer_generator.cpp.obj:
	$(MAKE) -f CMakeFiles\java_compiler.dir\build.make CMakeFiles/java_compiler.dir/lexical_analyzer_generator/lexical_analyzer_generator.cpp.obj
.PHONY : lexical_analyzer_generator/lexical_analyzer_generator.cpp.obj

lexical_analyzer_generator/lexical_analyzer_generator.i: lexical_analyzer_generator/lexical_analyzer_generator.cpp.i

.PHONY : lexical_analyzer_generator/lexical_analyzer_generator.i

# target to preprocess a source file
lexical_analyzer_generator/lexical_analyzer_generator.cpp.i:
	$(MAKE) -f CMakeFiles\java_compiler.dir\build.make CMakeFiles/java_compiler.dir/lexical_analyzer_generator/lexical_analyzer_generator.cpp.i
.PHONY : lexical_analyzer_generator/lexical_analyzer_generator.cpp.i

lexical_analyzer_generator/lexical_analyzer_generator.s: lexical_analyzer_generator/lexical_analyzer_generator.cpp.s

.PHONY : lexical_analyzer_generator/lexical_analyzer_generator.s

# target to generate assembly for a file
lexical_analyzer_generator/lexical_analyzer_generator.cpp.s:
	$(MAKE) -f CMakeFiles\java_compiler.dir\build.make CMakeFiles/java_compiler.dir/lexical_analyzer_generator/lexical_analyzer_generator.cpp.s
.PHONY : lexical_analyzer_generator/lexical_analyzer_generator.cpp.s

lexical_analyzer_generator/nfa_creator.obj: lexical_analyzer_generator/nfa_creator.cpp.obj

.PHONY : lexical_analyzer_generator/nfa_creator.obj

# target to build an object file
lexical_analyzer_generator/nfa_creator.cpp.obj:
	$(MAKE) -f CMakeFiles\java_compiler.dir\build.make CMakeFiles/java_compiler.dir/lexical_analyzer_generator/nfa_creator.cpp.obj
.PHONY : lexical_analyzer_generator/nfa_creator.cpp.obj

lexical_analyzer_generator/nfa_creator.i: lexical_analyzer_generator/nfa_creator.cpp.i

.PHONY : lexical_analyzer_generator/nfa_creator.i

# target to preprocess a source file
lexical_analyzer_generator/nfa_creator.cpp.i:
	$(MAKE) -f CMakeFiles\java_compiler.dir\build.make CMakeFiles/java_compiler.dir/lexical_analyzer_generator/nfa_creator.cpp.i
.PHONY : lexical_analyzer_generator/nfa_creator.cpp.i

lexical_analyzer_generator/nfa_creator.s: lexical_analyzer_generator/nfa_creator.cpp.s

.PHONY : lexical_analyzer_generator/nfa_creator.s

# target to generate assembly for a file
lexical_analyzer_generator/nfa_creator.cpp.s:
	$(MAKE) -f CMakeFiles\java_compiler.dir\build.make CMakeFiles/java_compiler.dir/lexical_analyzer_generator/nfa_creator.cpp.s
.PHONY : lexical_analyzer_generator/nfa_creator.cpp.s

lexical_analyzer_generator/nfa_dfa_converter.obj: lexical_analyzer_generator/nfa_dfa_converter.cpp.obj

.PHONY : lexical_analyzer_generator/nfa_dfa_converter.obj

# target to build an object file
lexical_analyzer_generator/nfa_dfa_converter.cpp.obj:
	$(MAKE) -f CMakeFiles\java_compiler.dir\build.make CMakeFiles/java_compiler.dir/lexical_analyzer_generator/nfa_dfa_converter.cpp.obj
.PHONY : lexical_analyzer_generator/nfa_dfa_converter.cpp.obj

lexical_analyzer_generator/nfa_dfa_converter.i: lexical_analyzer_generator/nfa_dfa_converter.cpp.i

.PHONY : lexical_analyzer_generator/nfa_dfa_converter.i

# target to preprocess a source file
lexical_analyzer_generator/nfa_dfa_converter.cpp.i:
	$(MAKE) -f CMakeFiles\java_compiler.dir\build.make CMakeFiles/java_compiler.dir/lexical_analyzer_generator/nfa_dfa_converter.cpp.i
.PHONY : lexical_analyzer_generator/nfa_dfa_converter.cpp.i

lexical_analyzer_generator/nfa_dfa_converter.s: lexical_analyzer_generator/nfa_dfa_converter.cpp.s

.PHONY : lexical_analyzer_generator/nfa_dfa_converter.s

# target to generate assembly for a file
lexical_analyzer_generator/nfa_dfa_converter.cpp.s:
	$(MAKE) -f CMakeFiles\java_compiler.dir\build.make CMakeFiles/java_compiler.dir/lexical_analyzer_generator/nfa_dfa_converter.cpp.s
.PHONY : lexical_analyzer_generator/nfa_dfa_converter.cpp.s

main.obj: main.cpp.obj

.PHONY : main.obj

# target to build an object file
main.cpp.obj:
	$(MAKE) -f CMakeFiles\java_compiler.dir\build.make CMakeFiles/java_compiler.dir/main.cpp.obj
.PHONY : main.cpp.obj

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles\java_compiler.dir\build.make CMakeFiles/java_compiler.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles\java_compiler.dir\build.make CMakeFiles/java_compiler.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... java_compiler
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... lexical_analyzer_generator/finite_automata/finite_automata.obj
	@echo ... lexical_analyzer_generator/finite_automata/finite_automata.i
	@echo ... lexical_analyzer_generator/finite_automata/finite_automata.s
	@echo ... lexical_analyzer_generator/finite_automata/state.obj
	@echo ... lexical_analyzer_generator/finite_automata/state.i
	@echo ... lexical_analyzer_generator/finite_automata/state.s
	@echo ... lexical_analyzer_generator/lexical_analyzer_generator.obj
	@echo ... lexical_analyzer_generator/lexical_analyzer_generator.i
	@echo ... lexical_analyzer_generator/lexical_analyzer_generator.s
	@echo ... lexical_analyzer_generator/nfa_creator.obj
	@echo ... lexical_analyzer_generator/nfa_creator.i
	@echo ... lexical_analyzer_generator/nfa_creator.s
	@echo ... lexical_analyzer_generator/nfa_dfa_converter.obj
	@echo ... lexical_analyzer_generator/nfa_dfa_converter.i
	@echo ... lexical_analyzer_generator/nfa_dfa_converter.s
	@echo ... main.obj
	@echo ... main.i
	@echo ... main.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

