# METHOD_BODY = STATEMENT_LIST
# STATEMENT_LIST = STATEMENT STATEMENT_LIST1
# STATEMENT_LIST1 = STATEMENT STATEMENT_LIST1 | '\L'
# STATEMENT = DECLARATION | IF | WHILE | ASSIGNMENT
# DECLARATION = PRIMITIVE_TYPE 'id' ';'
# PRIMITIVE_TYPE = 'int' | 'float'
# IF = 'if' '(' EXPRESSION ')' '{' STATEMENT '}' 'else' '{' STATEMENT '}'
# WHILE = 'while' '(' EXPRESSION ')' '{' STATEMENT '}'
# ASSIGNMENT = 'id' 'assign' EXPRESSION ';'
# EXPRESSION = SIMPLE_EXPRESSION EXPRESSION1
# EXPRESSION1 = 'relop' SIMPLE_EXPRESSION | '\L'
# SIMPLE_EXPRESSION = TERM SIMPLE_EXPRESSION1 | SIGN TERM SIMPLE_EXPRESSION1
# SIMPLE_EXPRESSION1 = 'addop' TERM SIMPLE_EXPRESSION1 | '\L'
# TERM = FACTOR TERM1
# TERM1 = 'mulop' FACTOR TERM1 | '\L'
# FACTOR = 'id' | 'num' | '(' EXPRESSION ')'
# SIGN = '+' | '-'
