# METHOD_BODY =
	@INIT_CODE
	STATEMENT_LIST
	#STATEMENT_LIST_RECORD
	M
	#M_RECORD
	@METHOD_BODY_ACTION
	@FINALIZE_CODE

# STATEMENT_LIST =
 	STATMENT
	#STATMENT_RECORD
	M
  	#M_RECORD
  	STATEMENT_LIST1
  	#STATEMENT_LIST1_RECORD
  	@STATEMENT_LIST1_ACTION

# STATEMENT_LIST1 =
 	STATEMENT
 	#STATEMENT_RECORD_STATEMENT_LIST1
 	M
 	#M_RECORD_STATEMENT_LIST1
 	STATEMENT_LIST1
 	#STATEMENT_LIST1_RECORD_STATEMENT_LIST1
	@STATEMENT_LIST1_ACTION_STATEMENT_LIST1
	|
	'\L'


# STATEMENT =
	DECLARATION
	|
	IF
	#IF_RECORD
	|
	WHILE
	#WHILE_RECORD
	|
	ASSIGNMENT



# DECLARATION =
 	PRIMITIVE_TYPE
 	#PRIMITIVE_TYPE_RECORD_DECLARATION
 	'id'
 	@id_ACTION_DECLARATION
 	';'
 	@DECLARATION_ACTION_DECLARATION


# PRIMITIVE_TYPE =
	'int'
	@int_ACTION_PRIMITIVE_TYPE
	|
	'float'
	@float_ACTION_PRIMITIVE_TYPE


# IF =
	'if'
	'('
	EXPRESSION
	#EXPRESSION_RECORD_IF
	')'
	'{'
	M
	#M1_RECORD_IF
	STATEMENT
	#STATEMENT1_RECORD_IF
	@GOTO_ACTION_IF
	'}'
	'else'
	'{'
	M
	#M2_RECORD_IF
	STATEMENT
	#STATEMENT2_RECORD_IF
	'}'
	@IF_ACTION_IF

# WHILE =
	M
	#M1_RECORD_WHILE
	'while'
	'('
	EXPRESSION
	#EXPRESSION_RECORD_WHILE
	')'
	'{'
	M
	#M2_RECORD_WHILE
	STATEMENT
	#STATEMENT_RECORD_WHILE
	'}'
	@WHILE_ACTION_WHILE

# ASSIGNMENT =
	'id'
	@id_ACTION_ASSIGNMENT
	'='
	EXPRESSION
	#EXPRESSION_RECORD_ASSIGNMENT
	';'
	@ASSIGNMENT_ACTION_ASSIGNMENT

# EXPRESSION =
	SIMPLE_EXPRESSION
	#SIMPLE_EXPRESSION_RECORD_EXPRESSION
	EXPRESSION1
	#EXPRESSION1_RECORD_EXPRESSION

# EXPRESSION1 =
	@EXPRESSION1_IN_relop
 	'relop'
 	@relop_ACTION
 	SIMPLE_EXPRESSION
 	#SIMPLE_EXPRESSION_RECORD_EXPRESSION1
 	@EXPRESSION1_ACTION_relop
 	|
 	@EXPRESSION1_IN_eps
 	'\L'
 	EXPRESSION1_ACTION_eps


# SIMPLE_EXPRESSION =
	TERM
	#TERM_RECORD_SIMPLE_EXPRESSION
	SIMPLE_EXPRESSION1
	#SIMPLE_EXPRESSION1_RECORD_SIMPLE_EXPRESSION


# SIMPLE_EXPRESSION1 =
	@SIMPLE_EXPRESSION1_IN_addop
 	'addop'
 	@addop_ACTION
 	TERM
 	#TERM_RECORD_SIMPLE_EXPRESSION1
 	@SIMPLE_EXPRESSION1_ACTION_addop
 	#SIMPLE_EXPRESSION1_RECORD_SIMPLE_EXPRESSION1
 	|
 	@SIMPLE_EXPRESSION1_IN_eps
 	'\L'
 	@SIMPLE_EXPRESSION1_ACTION_eps


# TERM =
 	FACTOR
 	#FACTOR_RECORD_TERM
 	TERM1
 	#TERM1_RECORD_TERM



# TERM1 =
 	@TERM1_IN_mulop
 	'mulop'
 	@mulop_ACTION
 	FACTOR
 	#FACTOR_RECORD_TERM1
 	@TERM1_ACTION_mulop
 	TERM1
 	#TERM1_RECORD_TERM1
 	|
 	@TERM1_IN_eps
 	'\L'
 	@TERM1_ACTION_eps

# FACTOR =
 	'id'
 	@id_ACTION_FACTOR
 	@FACTOR_ACTION_FACTOR_id
 	|
 	'num'
 	@num_ACTION_FACTOR
 	@FACTOR_ACTION_FACTOR_num
 	|
 	'('
 	SIMPLE_EXPRESSION
 	#SIMPLE_EXPRESSION_RECORD
 	')'
 	@FACTOR_ACTION_FACTOR_PAREN

# M = '\L'

